### ISSUE TITLE
chart scale not very clean when using mmol/l

### ISSUE THREAD

**Issue by midnightcoup** [creepymonster/GlucoseDirectApp#132]
I understand that the chart's scale is just a direct conversion from 50 - 350 mg/dL. However, when using mmol/l, this is between 2.8 mmol/l to 19.4 mmol/l. Not having whole number scale on the graph makes it less readable.

Would suggest implementing a different scale when using mmol/l. For example -- 2 mmol/l to 20 mmmol/l.

**Comment by creepymonster** [comment]
That is a good suggestion, I will adjust the scale for mmol.

**Comment by creepymonster** [comment]
I have adjusted the scale for mmol. In main branch here at GitHub the change is already committed, at TestFlight an update will come in the next few days.

Many greetings
