### ISSUE TITLE
Support for Libre 2 US without transmitter

### ISSUE THREAD

**Issue by xambu** [creepymonster/GlucoseDirectApp#201]
Libre 2 US now has an app that allows it to be used without the hardware reader. However, none of the transmitters work as far as I can tell. 
How do I get this working? If you can point me in the right direction, I will try to get it working and send you a diff. 
I have not programmed in swift but, if I know how the EU version was hacked, I can do the same for the US version.

**Comment by creepymonster** [comment]
Unfortunately, the US version works completely differently. So far, the Libre 2 US/CA sensors, just like the 3s, could not be decrypted.

As far as I know, the Libre 2 US/CA sensors currently only work with the transmitters and the app from https://www.ambrosiasys.com.

These are apparently allowed to use Abbott's SDK.
