### ISSUE TITLE
Any plans to add support for Libre Pro sensors?

### ISSUE THREAD

**Issue by varunmashru** [creepymonster/GlucoseDirectApp#213]
Majority of users in India use Libre Pro sensors with MiaoMiao transmitters. It's supposed to be used with the Tomato app but it is proving to be highly unreliable recently. Also, it's no longer available on the App store either. It would amazing if you could add support for Libre Pro. 
I can contribute as a Product Designer but unfortunately have no experience in Swift.

**Comment by gui-dos** [comment]
Recently @prakashdevadas69 sent me some detailed logs (https://github.com/gui-dos/DiaBLE/discussions/2) and certainly it is possible to communicate successfully with a Libre Pro / MiaoMiao3 / Bubble by slightly modifying the current solutions. The 43 blocks sent via BLE by the MiaoMiao however have a different FRAM layout than the Libre 1/2 therefore a new specific subclass to support it (and the 14-day historic data) has to be written. I am trying to implement it at https://github.com/gui-dos/DiaBLE/blob/main/DiaBLE/LibrePro.swift but I never tested Libre Pros physically.

**Comment by creepymonster** [comment]
I would have liked to add iOS 16 support.

I also tried to get Libre Pro sensors from Ebay or other sources on the internet, but could not get anything.

Unfortunately, they can't support the Libre Pro without sensors to test.
