### ISSUE TITLE
adding manual BG while waiting for sensor

### ISSUE THREAD

**Issue by mountrcg** [creepymonster/GlucoseDirectApp#37]
I was waiting for a virtual sensor connection and added a manual Glucose Reading in List. This initiated the graph on Overview with the sensor connection state output below
![Simulator Screen Shot - iPhone 13 mini - 2021-12-09 at 09 49 13](https://user-images.githubusercontent.com/539276/145364290-d0158adc-11a8-4615-9270-6741d956e438.png)

**Comment by mountrcg** [comment]
So I guess the issue is the tint of the footer, which after the sensor is initialized looks fine again
![Simulator Screen Shot - iPhone 13 mini - 2021-12-09 at 10 09 31](https://user-images.githubusercontent.com/539276/145367433-7751a30f-b682-407e-9653-2f48a5da59b8.png)

**Comment by creepymonster** [comment]
Thank you for the second screenshot. I don't know yet exactly why the navigation in the simulator (only in the simulator I could observe the problem) has no background color. But I haven't really been able to find out anything about it yet either.

**Comment by mountrcg** [comment]
Also on iphone not just simulator
![BA01CB3D-D3A7-4BC4-A8CE-C6C541FA8436](https://user-images.githubusercontent.com/539276/145536632-7eb9d456-439c-425a-a101-de1943c020a3.jpeg)
