### ISSUE TITLE
Libre US 14 days, Libre Pro/h

### ISSUE THREAD

**Issue by Bubblandevteam** [creepymonster/GlucoseDirectApp#63]
New Features : Requesting support for Libre US 14 days, Libre Pro/h with Bubble transmitter.

**Comment by creepymonster** [comment]
I am sorry, I am afraid I will not be able to provide this support. I own a Bubble Transmitter (with which I could develop and test the connection), but I have no access to Libre US 14, Libre Pro/h sensors to deal with.

Does the Bubble Transmitter (depending on firmware version) support decryption of both sensors (via command [0x08, 0x01, 0x00, 0x00, 0x2B] - similar to Libre 2)?

**Comment by bubbledevteam** [comment]
> I am sorry, I am afraid I will not be able to provide this support. I own a Bubble Transmitter (with which I could develop and test the connection), but I have no access to Libre US 14, Libre Pro/h sensors to deal with.
> 
> Does the Bubble Transmitter (depending on firmware version) support decryption of both sensors (via command [0x08, 0x01, 0x00, 0x00, 0x2B] - similar to Libre 2)?

yes,you can get decrypted data with 0x08 command for Libre 2 EU and Libre US 14 ,but I don't recommend use this with LibrePro for I don't finish the glucose Algorithm for this type so far

**Comment by creepymonster** [comment]
Thanks a lot, I will have a look and then implement it.
