### ISSUE TITLE
nightscout upload doesn't work

### ISSUE THREAD

**Issue by midnightcoup** [creepymonster/GlucoseDirectApp#71]
Hello,

Thank you for this app. I noticed that nightscout upload isn't working even if I added the url and API secret. Is this expected?

Regards.

**Comment by creepymonster** [comment]
Thanks for the info. Both must be entered - Nightscout URL and API_Secret.

The URL for example in the form:
https://my-nightscout.herokuapp.com

If that doesn't help I would be happy if you could send me the logfile under "Settings" at the bottom. To reimarmetzen@gmail.com

Many greetings

**Comment by berpj** [comment]
> The URL for example in the form: https://my-nightscout.herokuapp.com
Thanks, at first I didn't enter "https://" and it wasn't working for me neither.

It says "Host" in the app: I think "URL" would be a better description, and maybe a placeholder could be useful.

Thank you for this app.

**Comment by creepymonster** [comment]
That is a good idea. I will include a placeholder and pay attention to the protocol - renaming is also a good hint. I will implement the suggestions for improvement and validate the inputs.

Many greetings

**Comment by creepymonster** [comment]
I implemented your suggestion in the next update.

**Comment by midnightcoup** [comment]
Ah, yes. It was https:// missing. Thank you.
