### ISSUE TITLE
inaccuracy in glucose readings

### ISSUE THREAD

**Issue by midnightcoup** [creepymonster/GlucoseDirectApp#73]
The readings tend to be over 1.5 mmol/l (around 30 mg/dl) off from Freestyle Libre app and from xDrip using Libre algorithm (OOP2). xDrip with Libre algorithm is much closer to the readings on the Libre app and from a finger prick test.

Which algorithm is being used here? Are there plans to implement the OOP2?

**Comment by creepymonster** [comment]
Unfortunately, such problems could not be found yet. The algorithm is the well-known one that is used in this way (or something similar) in all apps.

OOP2 support is not planned.

In general, it is recommended to calibrate the sensor with blood glucose values.
